/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_management_system;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kwame
 */

public class RegStudent extends javax.swing.JFrame {

    String StdNo;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form RegStudent
     */
    public RegStudent() {
        initComponents();
        conn = MyConnection.Connect();
        getStdId();
        getStdNoCount();
    }

    String imgPath = null;
    String gender;
    String Sponsor;
    
    int mousepX;
    int mousepY;
    
    //CLOSE FORM
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    //resize Image
    public ImageIcon ResizeImage(String ImagePath, byte[] pic){
        
        ImageIcon MyImage = null;
        if(ImagePath != null){
            MyImage = new ImageIcon(ImagePath);
        }
        else{
            MyImage = new ImageIcon(pic);
        }
        //get and scale image
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblPic.getWidth(), lblPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        
        return image;
    }
    
    //get last std number + 1
    private void getStdId(){
        try{
        String sql = "select max(Std_Id) from students";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        
        if(rs.next()){
            int getId = rs.getInt("max(Std_Id)");
            if(getId == 0){
            getId = getId + 1;
            }
            else{
            getId = getId + 1;
            }
            String StdId = String.valueOf(getId);
            lblStdId.setText(" STD000" + StdId);
        }
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        finally{
            try{
                rs.close();
                ps.close();
            }
            catch(SQLException exc){
               JOptionPane.showMessageDialog(null,exc.getMessage());
            }
        }
    }
        
    // count no of students
    private void getStdNoCount(){
        try{
        String sql = "select count(Std_Id) from students";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        
        if(rs.next()){
            int get = rs.getInt("count(Std_Id)");
            if(get == 0){
            get = get + 1;
            }
            else{
            get = get + 1;
            }
            StdNo = String.valueOf(get);
            txtStudentNumber.setText(" " + StdNo);
        }
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        finally{
            try{
                rs.close();
                ps.close();
            }
            catch(SQLException exc){
               JOptionPane.showMessageDialog(null,exc.getMessage());
            }
        }
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblPic = new javax.swing.JLabel();
        btnAddPicture = new javax.swing.JButton();
        txtLastname = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        txtAddress = new javax.swing.JTextField();
        cboClass = new javax.swing.JComboBox();
        cboFees = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdbParent = new javax.swing.JRadioButton();
        txtSpName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSpPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rdbGuardian = new javax.swing.JRadioButton();
        txtSpAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtDOB = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        txtDOA = new com.toedter.calendar.JDateChooser();
        lblStdId = new javax.swing.JLabel();
        txtStudentNumber = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 29, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_student_registration_100px_1.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Add new student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(0, 629, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 940, 100));

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 103, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lastname");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 168, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 316, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Date of birth");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 242, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Class");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 449, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fees");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 168, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Student No.");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 36, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Address");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 382, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Picture");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 15, -1, -1));

        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 127, 228, 30));

        lblPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 154, 140));

        btnAddPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_pictures_folder_25px.png"))); // NOI18N
        btnAddPicture.setText("Add Picture");
        btnAddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPictureActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 120, -1));

        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 194, 228, 30));

        rdbMale.setBackground(new java.awt.Color(251, 251, 251));
        rdbMale.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });
        jPanel2.add(rdbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 338, -1, -1));

        rdbFemale.setBackground(new java.awt.Color(251, 251, 251));
        rdbFemale.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbFemale.setText("Female");
        rdbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(rdbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 338, -1, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 408, 228, 30));

        cboClass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cboClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nursery 1", "Nursery 2", "K.G 1", "K.G 2", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "J.H.S 1", "J.H.S 2", "J.H.S 3" }));
        jPanel2.add(cboClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 475, 228, 30));

        cboFees.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cboFees.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GH₵70.00", "GH₵90.00", "GH₵1000.00", "GH₵120.30", "GH₵125.50", "GH₵129.00", "GH₵150.00", "GH₵163.00", "GH₵155.00" }));
        jPanel2.add(cboFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 194, 228, 30));

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sponsor"));
        jPanel4.setForeground(new java.awt.Color(0, 153, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Select Sponsor");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Phone No.");

        rdbParent.setBackground(new java.awt.Color(251, 251, 251));
        rdbParent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbParent.setText("Parent");
        rdbParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbParentActionPerformed(evt);
            }
        });

        txtSpName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Address");

        txtSpPhone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Sponsor's name");

        rdbGuardian.setBackground(new java.awt.Color(251, 251, 251));
        rdbGuardian.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbGuardian.setText("Guardian");
        rdbGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGuardianActionPerformed(evt);
            }
        });

        txtSpAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtSpName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdbParent)
                        .addGap(18, 18, 18)
                        .addComponent(rdbGuardian))
                    .addComponent(txtSpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtSpPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbParent)
                    .addComponent(rdbGuardian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSpName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(txtSpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addComponent(txtSpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 230, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_save_close_25px.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 534, 98, 35));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_home_25px_1.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 534, 104, 35));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_add_25px_1.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 534, 92, 35));

        txtDOB.setDateFormatString("yyyy-MM-d");
        jPanel2.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 268, 228, 30));

        jLabel18.setText("Date Of Admission");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 108, -1, -1));

        txtDOA.setDateFormatString("yyyy-MM-d");
        jPanel2.add(txtDOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 127, 228, 30));

        lblStdId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStdId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblStdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 62, 228, 30));

        txtStudentNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStudentNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtStudentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 62, 228, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 940, 580));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_school_house_30px.png"))); // NOI18N

        btnback.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(116, 116, 119));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management_system/Images/icons8_chevron_left_round_30px.png"))); // NOI18N
        btnback.setText("Back");
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(btnback)
                .addGap(0, 822, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(btnback))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        new Register().setVisible(true);
        close();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MainS().setVisible(true);
        close();
    }//GEN-LAST:event_btnHomeActionPerformed

    //Add picture
    private void btnAddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPictureActionPerformed
        // TODO add your handling code here:
        JFileChooser choser = new JFileChooser();
        choser.setCurrentDirectory(new File(System.getProperty("user.home")));
        ///filter the files for images
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","png");
        choser.addChoosableFileFilter(filter);
        int result = choser.showOpenDialog(null);
        // if the user clicks open button
        if(result == JFileChooser.APPROVE_OPTION){
            File sf = choser.getSelectedFile();
            String path = sf.getAbsolutePath();
            lblPic.setIcon(ResizeImage(path,null));
            
            imgPath = path;
        } 
        
    }//GEN-LAST:event_btnAddPictureActionPerformed

    //Save Items to database
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtStudentNumber.getText().trim().isEmpty() || txtFirstname.getText().trim().isEmpty() || txtLastname.getText().trim().isEmpty() || txtAddress.getText().trim().isEmpty() || txtDOB.getDate().toString().trim().isEmpty() || txtDOA.getDate().toString().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in the details");
        }
        if(imgPath != null)
           {
                try{
                    String sql = "insert into students(Std_No,Std_Card_Id,Firstname,Lastname,DOB,DOA,Gender,Address,Picture,Class,Fees,Sponsor_Type,Sp_Name,Sp_Contact,Sp_Address) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    ps=conn.prepareStatement(sql);
                    //ps.setString(1, txtEmployeeId.getText());
                    ps.setString(1, txtStudentNumber.getText());
                    ps.setString(2, lblStdId.getText());
                    ps.setString(3, txtFirstname.getText());
                    ps.setString(4, txtLastname.getText());
                    ps.setString(5,  ((JTextField)txtDOB.getDateEditor().getUiComponent()).getText());
                    ps.setString(6, ((JTextField)txtDOA.getDateEditor().getUiComponent()).getText());
                    ps.setString(7, gender);
                    ps.setString(8, txtAddress.getText());
                    //saving image
                    try {
                        InputStream img = new FileInputStream(new File(imgPath));
                        ps.setBlob(9, img);
                       
                        
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(RegEmp.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ps.setString(10, cboClass.getSelectedItem().toString());
                    ps.setString(11, cboFees.getSelectedItem().toString());
                    ps.setString(12, Sponsor);
                    ps.setString(13, txtSpName.getText());
                    ps.setString(14, txtSpPhone.getText());
                    ps.setString(15, txtSpAddress.getText());

                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null, "Items Saved successfully!!");
                    }
                    catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                    finally{
                        try{
                            rs.close();
                            ps.close();
                           }
                        catch(SQLException ex){
                           JOptionPane.showMessageDialog(null,ex.getMessage());
                        }
            
                    }
                //JOptionPane.showMessageDialog(null, "Items Saved successfully!!");
           }
           else{
               JOptionPane.showMessageDialog(null, "Item was not saved!!!");
           }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        gender = "Male";
    }//GEN-LAST:event_rdbMaleActionPerformed

    private void rdbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFemaleActionPerformed
        gender = "Female";
    }//GEN-LAST:event_rdbFemaleActionPerformed

    private void rdbParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbParentActionPerformed
        Sponsor = "Parent";
    }//GEN-LAST:event_rdbParentActionPerformed

    private void rdbGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGuardianActionPerformed
        Sponsor = "Guardian";
    }//GEN-LAST:event_rdbGuardianActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtFirstname.setText("");
        txtLastname.setText("");
        txtAddress.setText("");
        txtStudentNumber.setText("");
        txtSpName.setText("");
        txtSpPhone.setText("");
        txtSpAddress.setText("");
        lblPic.setIcon(null);
    }//GEN-LAST:event_btnNewActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int cordinateX = evt.getXOnScreen();
        int cordinateY = evt.getYOnScreen();
        
        this.setLocation(cordinateX-mousepX,cordinateY-mousepY);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPicture;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnback;
    private javax.swing.JComboBox cboClass;
    private javax.swing.JComboBox cboFees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblStdId;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbGuardian;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JRadioButton rdbParent;
    private javax.swing.JTextField txtAddress;
    private com.toedter.calendar.JDateChooser txtDOA;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtSpAddress;
    private javax.swing.JTextField txtSpName;
    private javax.swing.JTextField txtSpPhone;
    private javax.swing.JLabel txtStudentNumber;
    // End of variables declaration//GEN-END:variables
}
